# Generated by Django 3.2.7 on 2021-09-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('checker_id', models.AutoField(primary_key=True, serialize=False)),
                ('checker_name', models.CharField(max_length=45)),
                ('charge_state', models.CharField(blank=True, max_length=45, null=True)),
                ('charge_city', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'checker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('lift_id', models.AutoField(primary_key=True, serialize=False)),
                ('lift_name', models.CharField(blank=True, max_length=45, null=True)),
                ('lift_status', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('addr_state', models.CharField(max_length=45)),
                ('addr_city', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'lift',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Liftcheck',
            fields=[
                ('check_id', models.AutoField(primary_key=True, serialize=False)),
                ('lift_id', models.IntegerField()),
                ('checker_id', models.IntegerField(blank=True, null=True)),
                ('checker_name', models.CharField(max_length=45)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'liftcheck',
                'managed': False,
            },
        ),
    ]
